spring:
  application:
    name: zuul
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

api:
  zuul:
    actuator:
      url:
        path: /actuator/*
  users:
    actuator:
      url:
        path: /users-ws/actuator/*
  h2console:
    url:
      path: /users-ws/h2-console/**
  registration:
    url:
      path: /users-ws/users
  login:
    url:
      path: /users-ws/users/login

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: my-secret

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace